config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users,
             skip: %I[password registrations],
             controllers: {
               sessions: 'admin/sessions'
             },
             path: '/admin',
             path_names: { sign_in: 'login' }

  devise_for :users,
             skip: %I[sessions registrations password],
             path: 'user'

  as :user do
    get 'user/sign_up', to: 'registrations#new', as: :new_user_registration
    post 'user', to: 'registrations#create', as: :user_registration
    get 'user/sign_in', to: 'sessions#new', as: :new_user_session
    post 'user/sign_in', to: 'sessions#create', as: :user_session
    delete 'user/sign_out', to: 'sessions#destroy', as: :destroy_user_session
  end

  root to: 'auctions#index'

  resources :auctions, only: %I[index show]
  resources :bids, only: [] do
    member do
      get :new
    end
  end

  # Admin namespace
  namespace :admin do
    root to: 'auctions#index'

    resources :auctions, only: %I[index new create]
  end
end

app/models/auction.rb
class Auction < ApplicationRecord
  has_attached_file :image,
                    styles: {
                      thumb: ['400x400#'],
                      tiny: ['200x200#'],
                      mini: ['100x100#']
                    }

  validates :start_value,
            :current_value,
            :ending_value,
            :name,
            :description,
            presence: true
  validates :image, attachment_presence: true
  validates :description,
            length: { maximum: 255 },
            allow_blank: true
  validates :name,
            length: { maximum: 40 },
            allow_blank: true
  validates :start_value,
            :current_value,
            :ending_value,
            numericality: { greater_than: 0 },
            allow_blank: true
  validates :ending, inclusion: { in: [true, false] }
  validate :lower_ending_value

  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\z}
  validates_attachment_content_type :image,
                                    content_type: [
                                      'image/jpeg',
                                      'image/pjpeg',
                                      'image/jpg',
                                      'image/x-png',
                                      'image/png',
                                      'image/gif'
                                    ]
  private

  def lower_ending_value
    return if ending_value.blank? || current_value.blank? ||
              ending_value > current_value

    errors.add(:ending_value, 'ending_value must be greater than start_value')
  end
end

app/controllers/admin/auctions_controller.rb
module Admin
  class AuctionsController < Admin::ApplicationController
    def index
      @auctions = Auction.all.order('created_at DESC').paginate(
        page: params[:page], per_page: 10
      )
    end

    def new
      @auction = Auction.new
      @auction.start_value = @auction.start_value.float_to_currency
      @auction.ending_value = @auction.ending_value.float_to_currency
    end

    def create
      @auction = Auction.new(permitted_params)
      @auction.current_value = @auction.start_value

      if @auction.save
        flash[:notice] = 'Lote cadastrado com sucesso'

        redirect_to admin_root_path
      else
        @auction.start_value = @auction.start_value.float_to_currency
        @auction.ending_value = @auction.ending_value.float_to_currency

        flash.now[:error] = @auction.errors.full_messages.first

        render :new
      end
    end

    private

    def permitted_params
      params[:auction][:start_value] = params[:auction][:start_value]
                                       .currency_to_float
      params[:auction][:ending_value] = params[:auction][:ending_value]
                                        .currency_to_float
      params.require(:auction).permit(
        :description, :start_value, :ending_value, :name, :image
      )
    end
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @auctions = Auction.all.order('created_at DESC').paginate(
      page: params[:page], per_page: 10
    )
  end
end

app/views/auctions/index.html.erb
<% content_for :title, "Auctions" -%>

<div class="em-wrapper-main">
  <div class="container container-main">
    <div class="em-inner-main">
      <div class="em-main-container em-col1-layout">
        <div class="row">
          <div class="em-line-01 em-col-main col-sm-24">
            <div class="widget-title">
              <h1><span>Auctions</span></h1>
            </div>
            <div class="category-products">
              <% if @auctions.blank? %>
              <p>No Auctions.</p>
              <% else %>
              <div id="em-grid-mode">
                <ul class="emcatalog-grid-mode products-grid emcatalog-disable-hover-below-mobile">
                  <% @auctions.each do |auction| %>
                  <li class="item" id="auction-<%= auction.id %>">
                    <div class="product-item">
                      <div class="product-shop-top">
                        <%= link_to auction_path(auction.id) do %>
                        <%= image_tag(auction.image.url(:tiny), class: 'em-img-lazy img-responsive') %>
                        <% end %>
                      </div>
                      <div class="product-shop">
                        <div class="f-fix">
                          <h2 class="product-name text-center  "><%= link_to auction.name, auction_path(auction.id) %></h2>
                          <div class="text-center price-box regular-price">
                            Current Value <span class="price" id="auction-value"><%= number_to_currency auction.current_value %></span>
                          </div>
                          <div class="text-center price-box regular-price">
                            Status <span class="price" id="auction-status"><%= auction.ending ? 'Closed' : 'Available' %></span>
                          </div>
                          <%= link_to bid_path(auction.id), remote: true do %>
                          <div class="points">
                            <div>Bid</div>
                          </div>
                          <% end %>
                        </div>
                      </div>
                    </div><!-- /.product-item -->
                  </li>
                  <% end %>
                </ul>
              </div><!-- /.em-grid-mode -->
              <% end %>

              <div class="toolbar-bottom em-box-03">
                <div class="toolbar">
                  <div class="pager">
                    <%= will_paginate @auctions %>
                  </div><!-- /.pager -->
                </div>
              </div><!-- /.toolbar-bottom -->
            </div><!-- /.category-products -->
          </div>
        </div>
      </div><!-- /.em-main-container -->
    </div>
  </div>
</div>

<% content_for :inline_javascript do %>
<script src="https://js.pusher.com/4.1/pusher.min.js"></script>

<script>
  // Enable pusher logging - don't include this in production
  <% if Rails.env == 'development' %>
  Pusher.logToConsole = true;
  <% end %>

  var pusher = new Pusher('78754a64770633d78f3f', {
    cluster: 'us2',
    encrypted: true
  });

  var channel = pusher.subscribe('auction');
  channel.bind('my-event', function(data) {
    $('#auction-' + data.id + ' #auction-value').text('R$ ' + data.value)
    if (data.ending === true){
      $('#auction-' + data.id + ' #auction-status').text('Arrematado')
    }
  });
</script>
<% end %>