config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users,
             skip: %I[password registrations],
             controllers: {
               sessions: 'admin/sessions'
             },
             path: '/admin',
             path_names: { sign_in: 'login' }

  devise_for :users,
             skip: %I[sessions registrations password],
             path: 'user'

  as :user do
    get 'user/sign_up', to: 'registrations#new', as: :new_user_registration
    post 'user', to: 'registrations#create', as: :user_registration
    get 'user/sign_in', to: 'sessions#new', as: :new_user_session
    post 'user/sign_in', to: 'sessions#create', as: :user_session
    delete 'user/sign_out', to: 'sessions#destroy', as: :destroy_user_session
  end

  root to: 'auctions#index'

  resources :auctions, only: %I[index show]
  resources :bids, only: [] do
    member do
      get :new
    end
  end

  # Admin namespace
  namespace :admin do
    root to: 'auctions#index'

    resources :auctions, only: %I[index new create]
  end
end

app/models/auction.rb
class Auction < ApplicationRecord
  has_attached_file :image,
                    styles: {
                      thumb: ['400x400#'],
                      tiny: ['200x200#'],
                      mini: ['100x100#']
                    }

  validates :start_value,
            :current_value,
            :ending_value,
            :name,
            :description,
            presence: true
  validates :image, attachment_presence: true
  validates :description,
            length: { maximum: 255 },
            allow_blank: true
  validates :name,
            length: { maximum: 40 },
            allow_blank: true
  validates :start_value,
            :current_value,
            :ending_value,
            numericality: { greater_than: 0 },
            allow_blank: true
  validates :ending, inclusion: { in: [true, false] }
  validate :lower_ending_value

  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\z}
  validates_attachment_content_type :image,
                                    content_type: [
                                      'image/jpeg',
                                      'image/pjpeg',
                                      'image/jpg',
                                      'image/x-png',
                                      'image/png',
                                      'image/gif'
                                    ]
  private

  def lower_ending_value
    return if ending_value.blank? || current_value.blank? ||
              ending_value > current_value

    errors.add(:ending_value, 'ending_value must be greater than start_value')
  end
end

app/controllers/admin/auctions_controller.rb
module Admin
  class AuctionsController < Admin::ApplicationController
    def index
      @auctions = Auction.all.order('created_at DESC').paginate(
        page: params[:page], per_page: 10
      )
    end

    def new
      @auction = Auction.new
      @auction.start_value = @auction.start_value.float_to_currency
      @auction.ending_value = @auction.ending_value.float_to_currency
    end

    def create
      @auction = Auction.new(permitted_params)
      @auction.current_value = @auction.start_value

      if @auction.save
        flash[:notice] = 'Lote cadastrado com sucesso'

        redirect_to admin_root_path
      else
        @auction.start_value = @auction.start_value.float_to_currency
        @auction.ending_value = @auction.ending_value.float_to_currency

        flash.now[:error] = @auction.errors.full_messages.first

        render :new
      end
    end

    private

    def permitted_params
      params[:auction][:start_value] = params[:auction][:start_value]
                                       .currency_to_float
      params[:auction][:ending_value] = params[:auction][:ending_value]
                                        .currency_to_float
      params.require(:auction).permit(
        :description, :start_value, :ending_value, :name, :image
      )
    end
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @auctions = Auction.all.order('created_at DESC').paginate(
      page: params[:page], per_page: 10
    )
  end
end

app/views/admin/auctions/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="main-box clearfix">
      <header class="main-box-header clearfix">
        <h2 class="pull-left">Lots</h2>

        <div id="reportrange" class="pull-right">
          <%= link_to 'New Lot', new_admin_auction_path, class: 'btn btn-primary' %>
        </div>
      </header>

      <div class="main-box-body clearfix">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th class="text-center"><span>id</span></th>
                <th class="text-center"><span>Product Name</span></th>
                <th class="text-center"><span>Initial Value</span></th>
                <th class="text-center"><span>Current Value</span></th>
                <th class="text-center"><span>Closed?</span></th>
                <th class="text-center"><span>Creation Date</span></th>
              </tr>
            </thead>
            <tbody>
              <% @auctions.each do |auction| %>
              <tr>
                <td class="text-center">#<%= auction.id %></td>
                <td><%= auction.name %></td>
                <td class="text-right"><%= number_to_currency auction.start_value %></td>
                <td class="text-right"><%= number_to_currency auction.current_value %></td>
                <td class="text-center">
                  <span class="label <%= auction.ending ? 'label-success' : 'label-danger' %>">
                    <%= auction_status_to_literal(auction.ending) %>
                  </span>
                </td>
                <td class="text-center"><%= l auction.created_at %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <ul class="pagination pull-right">
          <%= will_paginate @auctions %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/admin/auctions/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>New Lot</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="main-box">
      <%= simple_form_for(@auction, url: admin_auctions_path, method: :post) do |f| %>
        <header class="main-box-header clearfix">
          <h3><span>Details</span></h3>
        </header>
        <div class="main-box-body clearfix">
          <div class="row">
            <div class="form-group col-xs-6">
              <%= f.input :name %>
            </div>
            <div class="form-group col-xs-6">
              <%= f.input :description %>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-6">
              <%= f.input :start_value, as: :string, input_html: { :class => "money" , data: { 'mask' => '0.000.000.000,00', 'mask-reverse' => "true" }, maxlength: 15, length: 20} %>
            </div>
            <div class="form-group col-xs-6">
              <%= f.input :ending_value, as: :string, input_html: { :class => "money" , data: { 'mask' => '0.000.000.000,00', 'mask-reverse' => "true" }, maxlength: 15, length: 20} %>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12">
              <%= f.input :image, as: :file %>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12">
              <%= f.submit 'Submit', class: 'btn btn-success' %>
              <%= link_to 'Cancel', admin_auctions_path, class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>