config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users,
             skip: %I[password registrations],
             controllers: {
               sessions: 'admin/sessions'
             },
             path: '/admin',
             path_names: { sign_in: 'login' }

  devise_for :users,
             skip: %I[sessions registrations password],
             path: 'user'

  as :user do
    get 'user/sign_up', to: 'registrations#new', as: :new_user_registration
    post 'user', to: 'registrations#create', as: :user_registration
    get 'user/sign_in', to: 'sessions#new', as: :new_user_session
    post 'user/sign_in', to: 'sessions#create', as: :user_session
    delete 'user/sign_out', to: 'sessions#destroy', as: :destroy_user_session
  end

  root to: 'auctions#index'

  resources :auctions, only: %I[index show]
  resources :bids, only: [] do
    member do
      get :new
    end
  end

  # Admin namespace
  namespace :admin do
    root to: 'auctions#index'

    resources :auctions, only: %I[index new create]
  end
end

app/views/admin/shared/_breadcrumb.html.erb
<div class="row">
  <div class="col-lg-12">
    <div id="content-header" class="clearfix">
      <div class="pull-left">
        <ol class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li class="active"><span>Dashboard</span></li>
        </ol>

        <h1>Dashboard</h1>
      </div>

      <div class="pull-right hidden-xs">
        <div class="xs-graph pull-left">
          <div class="graph-label">
            <b><i class="fa fa-shopping-cart"></i> 838</b> Orders
          </div>
          <div class="graph-content spark-orders"></div>
        </div>

        <div class="xs-graph pull-left mrg-l-lg mrg-r-sm">
          <div class="graph-label">
            <b>&dollar;12.338</b> Revenues
          </div>
          <div class="graph-content spark-revenues"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/shared/_footer.html.erb
<footer id="footer-bar" class="row">
  <p id="footer-copyright" class="col-xs-12">
    Powered by Filipe Mendes
  </p>
</footer>

app/views/admin/shared/_header.html.erb
<header class="navbar" id="header-navbar">
  <div class="container">
    <a href="<%= admin_root_path %>" id="logo" class="navbar-brand">
      <%= image_tag("logo.png", class: "normal-logo logo-white") %>
      <%= image_tag("logo.png", class: "normal-logo logo-black") %>
      <%= image_tag("logo.png", class: "small-logo hidden-xs hidden-sm hidden") %>
    </a>

    <div class="clearfix">
      <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="fa fa-bars"></span>
      </button>

      <div class="nav-no-collapse pull-right" id="header-nav">
        <ul class="nav navbar-nav pull-right">
          <li class="dropdown profile-dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag('avatar_user.jpg', alt: '') %>
              <span class="hidden-xs"><%= current_admin_user.email %></span> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
            </ul>
          </li>
          <li>
            <a href="<%= destroy_admin_user_session_path %>" class="btn" data-method="delete" >
              <i class="fa fa-power-off"></i>
              <span class="hidden-xs">Logout</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/admin/shared/_menu_left.html.erb
<div id="nav-col">
  <section id="col-left" class="col-left-nano">
    <div id="col-left-inner" class="col-left-nano-content">
      <div class="collapse navbar-collapse navbar-ex1-collapse collapsing" id="sidebar-nav">
        <ul class="nav nav-pills nav-stacked">
          <li class="active">
            <%= link_to admin_auctions_path do %>
            <i class="fa fa-dashboard"></i>
            <span>Lots</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </section>
  <div id="nav-col-submenu"></div>
</div>